version: "3.9"
services:
  php-apache:
    image: koize/spmartweb:latest
    ports:
      - "80:80"
    build: './spmart'
    volumes:
      - ./spmart:/var/www/html
  mysql:
    image: koize/alpine-mariadb:latest
    ports:
      - "3306:3306"
    build: './sql'
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "spmart"
    volumes:
      - dbData:/var/lib/mysql
      - ./sql/spmart.sql:/docker-entrypoint-initdb.d/spmart.sql
      - ./sql/spmart.sql:/docker-entrypoint-initdb.d/reset_pass.sql

volumes:
  app:
  dbData:
  


